version: '3.8'

services:
  enclave-sgx:
    build:
      context: enclave
      dockerfile: Dockerfiles/SIM/Dockerfile
    environment:
      - ENCLAVE_DATABASE_URL=postgres://mercurylayer:<PASSWORD>@<DB_HOST>:5432/enclave
      - ENCLAVE_PORT=18080
      - SEED_DIR=./seed
  mercury-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - LOCKBOX_URL=http://enclave-sgx:18080
      - BITCOIN_NETWORK=testnet
      - LOCKHEIGHT_INIT=1000
      - LH_DECREMENT=10
      - DB_USER=mercurylayer
      - DB_PASSWORD=<CHANGEME>
      - DB_HOST=<CHANGEME>
      - DB_PORT=5432
      - DB_NAME=mercury
    ports:
      - "8000:8000"
  token-server:
    build:
      context: token-server
      dockerfile: Dockerfile
    environment:
      - processor_url = "http://0.0.0.0:18080"
      - api_key = "aaaaa"
      - fee = 10000
      - unit = "BTC"
      - delay = 3600
      - DB_USER = "mercurylayer"
      - DB_PASSWORD = "<CHANGEME>"
      - DB_HOST = "<CHANGEME>"
      - DB_PORT = 5432
      - DB_NAME = "mercury"
    ports:
      - "18080:18080"
  explorer:
    build:
      context: explorer
      dockerfile: Dockerfile
    ports:
      - "80:80"
