[general]
database_connection_string = "postgresql://postgres:postgres@localhost/enclave"
server_port = 18080
key_manager = "filesystem" # "google_kms", "hashicorp_container, "hashicorp_api", "filesystem"
[filesystem]
seed_filepath = "./seed"
[gcloud]
project_id = "mercury-441416"
project_number = "100600525477"
location_id = "global"
[secretmanager]
key_name = "encrypted-key"
[kms]
ring = "enclave"
crypto_key = "sealing"
[hashicorp_api]
hcp_client_id = ""
hcp_client_secret = ""
organization_id = ""
project_id = ""
app_name = ""
secret_name = ""
[hashicorp_container]
token = "2bbz80mr1zm0tfrjwxyq7f48ofgky848"
url = "http://127.0.0.1:8200"
path = "mercury-seed"
mount_point = "secret"
key_name = "seed"
